const {root,space,keep}=globalThis.cloudworldQA;
const task=await taskSpace(space??'Blender cave QA'),page=task.page('p1');
const assert=(ok,message)=>{if(!ok)throw Error(message);};
await page.cdp('Emulation.setFocusEmulationEnabled',{enabled:true});
await page.cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
await page.cdp('Page.addScriptToEvaluateOnNewDocument',{source:"window.__qaErrors=[];window.addEventListener('error',e=>window.__qaErrors.push(e.message));window.addEventListener('unhandledrejection',e=>window.__qaErrors.push(String(e.reason)));"});
await page.goto('http://localhost:5173');await page.waitForFunction(()=>window.__island?.ready,undefined,{timeout:30000});
assert(await page.evaluate(()=>window.__island.caveAsset?.triangles===798),'actual Blender GLB loaded');
console.log(await page.snapshot());
await page.click('loc=css:#enter-button');
await page.evaluate(()=>window.__islandTest.warp(13.2,1.8));
await page.keyboard.down('w');await page.keyboard.down('d');
try{await page.waitForFunction(()=>window.__island.cave>.8,undefined,{timeout:15000});}finally{await page.keyboard.up('w');await page.keyboard.up('d');}
await page.click('loc=css:#sound-button');await page.waitForFunction(()=>window.__island.audio.enabled,undefined,{timeout:15000});
await page.click('loc=css:#shout-button');await page.waitForFunction(()=>window.__island.audio.events.echoes>0);
let t=await page.evaluate(()=>window.__island.elapsed);await page.waitForFunction(t=>window.__island.elapsed>t+3,t,{timeout:15000});
await page.screenshot({path:`${root}/.playwright/blender-cave-interior.png`});
await page.evaluate(()=>window.__islandTest.warp(13.2,4.5));await page.click('loc=css:[data-period="sunset"]');
await page.waitForFunction(()=>window.__island.creatures.filter(c=>c.kind==='bird').every(c=>c.state==='perched'),undefined,{timeout:30000});
await page.screenshot({path:`${root}/.playwright/blender-cave-exterior.png`});
console.log(await page.evaluate(()=>({asset:window.__island.caveAsset,birds:window.__island.creatures.filter(c=>c.kind==='bird'),echoes:window.__island.audio.events.echoes,errors:window.__qaErrors})));
assert((await page.evaluate(()=>window.__qaErrors)).length===0,'desktop errors');
await page.click('loc=css:#sound-button');
await page.cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await page.evaluate(()=>window.__islandTest.warp(13.2,-5));
t=await page.evaluate(()=>window.__island.elapsed);await page.waitForFunction(t=>window.__island.elapsed>t+3,t,{timeout:15000});
await page.screenshot({path:`${root}/.playwright/blender-cave-mobile.png`});
assert(await page.evaluate(()=>document.documentElement.scrollWidth===390&&window.__island.cave>.8),'mobile cave view');
assert((await page.evaluate(()=>window.__qaErrors)).length===0,'mobile errors');
console.log('PASS: Blender GLB, physical entrance, cave echo, birds on ledge, desktop and mobile rendering.');
if(!keep)await task.finish({keep:[]});
