import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const args=process.argv.slice(2),spaceIndex=args.indexOf('--space');
const config={root:fileURLToPath(new URL('../',import.meta.url)).replace(/\/$/,''),space:spaceIndex<0?null:Number(args[spaceIndex+1]),keep:args.includes('--keep')};
const suiteIndex=args.indexOf('--suite'),suite=suiteIndex<0?'default':args[suiteIndex+1];
if(!['default','cave'].includes(suite))throw Error('Unknown QA suite');
const script=await readFile(new URL(suite==='cave'?'../tests/ego-cave-qa.mjs':'../tests/ego-qa.mjs',import.meta.url),'utf8');
const child=spawn('ego-browser',['nodejs'],{stdio:['pipe','inherit','inherit']});
child.stdin.end(`globalThis.cloudworldQA=${JSON.stringify(config)};\n${script}`);
child.on('error',error=>{console.error(error.message);process.exitCode=1;});
child.on('exit',code=>{process.exitCode=code??1;});
